apiVersion: spire.spiffe.io/v1alpha1
kind: ControllerManagerConfig
metrics:
  bindAddress: 127.0.0.1:8082
healthProbe:
  bindAddress: 127.0.0.1:8083
leaderElection:
  leaderElect: true
  resourceName: 98c9c988.spiffe.io
  resourceNamespace: spire-system
clusterName: cluster2
trustDomain: cluster2.demo
ignoreNamespaces:
  - kube-system
  - kube-public
  - spire-system
  - local-path-storage
  # - do not ignore vsecm-system!
  # - vsecm-system
  - kube-node-lease
  - kube-public
  - kubernetes-dashboard
