# /*
# |    Protect your secrets, protect your sensitive data.
# :    Explore VMware Secrets Manager docs at https://vsecm.com/
# </
# <>/  keep your secrets... secret
# >/
# <>/' Copyright 2023-present VMware Secrets Manager contributors.
# >/'  SPDX-License-Identifier: BSD-2-Clause
# */

apiVersion: batch/v1
kind: Job
metadata:
  name: spire-server-post-install
  namespace: spire-server
  labels:
    helm.sh/chart: spire-server-0.1.0
    app.kubernetes.io/name: server
    app.kubernetes.io/instance: spire
    app.kubernetes.io/version: "1.9.6"
    app.kubernetes.io/managed-by: Helm
  annotations:
    "helm.sh/hook": post-install
    "helm.sh/hook-delete-policy": before-hook-creation, hook-succeeded, hook-failed
spec:
  template:
    metadata:
      name: spire-server-post-install
    spec:
      restartPolicy: Never
      serviceAccountName: spire-server-post-install
      securityContext:
        fsGroup: 1000
        fsGroupChangePolicy: OnRootMismatch
        runAsGroup: 1000
        runAsUser: 1000
      containers:
        - name: post-install-job
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            readOnlyRootFilesystem: true
            runAsNonRoot: true
            seccompProfile:
              type: RuntimeDefault
          image: docker.io/rancher/kubectl:v1.28.0
          args:
            - patch
            - validatingwebhookconfiguration
            - spire-server-spire-controller-manager-webhook
            - --type=strategic
            - -p
            - |
              {
                "webhooks":[
                  {
                    "name":"vclusterspiffeid.kb.io",
                    "failurePolicy":"Fail"
                  },
                  {
                    "name":"vclusterfederatedtrustdomain.kb.io",
                    "failurePolicy":"Fail"
                  }
                ]
              }
