# /*
# |    Protect your secrets, protect your sensitive data.
# :    Explore VMware Secrets Manager docs at https://vsecm.com/
# </
# <>/  keep your secrets... secret
# >/
# <>/' Copyright 2023-present VMware Secrets Manager contributors.
# >/'  SPDX-License-Identifier: BSD-2-Clause
# */

# Service definition for SPIRE server bundle endpoint
apiVersion: v1
kind: Service
metadata:
  name: spire-server-bundle-endpoint
  namespace: {{ .Values.global.spire.serverNamespace }}
spec:
  type: {{ .Values.bundleEndpoint.type }}
  ports:
    - name: api
      port: {{ .Values.bundleEndpoint.port }}
      protocol: TCP
  selector:
    app: spire-server
