# /*
# |    Protect your secrets, protect your sensitive data.
# :    Explore VMware Secrets Manager docs at https://vsecm.com/
# </
# <>/  keep your secrets... secret
# >/
# <>/' Copyright 2023-present VMware Secrets Manager contributors.
# >/'  SPDX-License-Identifier: BSD-2-Clause
# */

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "keystone.fullname" . }}
  namespace: {{ .Values.global.vsecm.namespace }}
  labels:
    {{- include "keystone.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "keystone.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "keystone.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "keystone.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}

      priorityClassName: system-cluster-critical

      initContainers:
        - name: init-container
          image: "{{ .Values.global.registry }}/{{ .Values.global.images.initContainer.repository }}:{{ .Values.global.images.initContainer.tag }}"
          imagePullPolicy: {{ .Values.global.images.keystone.pullPolicy }}
          volumeMounts:
            - mountPath: /spire-agent-socket
              name: spire-agent-socket
              readOnly: true
          env:
            #
            # You can configure VSecM Init Container by providing
            # environment variables.
            #
            # See https://vsecm.com/configuration for more information about
            # these environment variables.
            #
            # When you don't explicitly provide env vars here, VMware Secrets Manager
            # Init Container will assume the default values outlined in the given link above.
            #
            {{- range .Values.initEnvironments }}
            - name: {{ .name }}
              value: {{ .value | quote }}
            {{- end }}
      containers:
        - name: main
          image: "{{ .Values.global.registry }}/{{- include "keystone.repository" .}}:{{ .Values.global.images.keystone.tag }}"
          imagePullPolicy: {{ .Values.global.images.keystone.pullPolicy }}
          volumeMounts:
            - name: spire-agent-socket
              mountPath: /spire-agent-socket
              readOnly: true
          #
          # You can configure VSecM Sentinel by providing
          # environment variables.
          #
          # See https://vsecm.com/configuration for more information about
          # these environment variables.
          #
          # When you don't explicitly provide env vars here, VMware Secrets Manager
          # Sentinel will assume the default values outlined in the given link above.
          #
          env:
            {{- range .Values.environments }}
            - name: {{ .name }}
              value: {{ .value | quote }}
            {{- end }}
          resources:
            requests:
              memory: {{ .Values.resources.requests.memory }}
              cpu: {{ .Values.resources.requests.cpu }}
      volumes:
        # Using SPIFFE CSI Driver to bind to the SPIRE Agent Socket
        # ref: https://github.com/spiffe/spiffe-csi
        - name: spire-agent-socket
          csi:
            driver: "csi.spiffe.io"
            readOnly: true
