# /*
# |    Protect your secrets, protect your sensitive data.
# :    Explore VMware Secrets Manager docs at https://vsecm.com/
# </
# <>/  keep your secrets... secret
# >/
# <>/' Copyright 2023-present VMware Secrets Manager contributors.
# >/'  SPDX-License-Identifier: BSD-2-Clause
# */

# -- Number of replicas to deploy. Note that values greater than 1 are not
# supported yet.
replicaCount: 1

# -- The port that the liveness probe listens on.
livenessPort: 8081

# -- See https://vsecm.com/configuration for more information
# about these environment variables.
environments:
 # -- The SPIFFE endpoint socket. This is used to communicate with the SPIRE.
 - name: SPIFFE_ENDPOINT_SOCKET
   value: "unix:///spire-agent-socket/agent.sock"
 # -- The interval between retries (in milliseconds) for the default backoff strategy.
 - name: VSECM_BACKOFF_DELAY
   value: "1000"
 # -- The maximum number of retries for the default backoff strategy before it gives up.
 - name: VSECM_BACKOFF_MAX_RETRIES
   value: "10"
 # -- The maximum wait time (in milliseconds) for the default backoff strategy.
 - name: VSECM_BACKOFF_MAX_WAIT
   value: "10000"
 # -- The backoff mode. The default is "exponential".
 # Allowed values: "exponential", "linear"
 - name: VSECM_BACKOFF_MODE
   value: "exponential"
 # -- The log level. 0: Logs are off (only audit events will be logged),
 # 7: TRACE level logging (maximum verbosity).
 - name: VSECM_LOG_LEVEL
   value: "7"
 # -- Useful for debugging. This will log cryptographic fingerprints of
 # secrets without revealing the secret itself. It is recommended to keep
 # this "false" in production.
 - name: VSECM_LOG_SECRET_FINGERPRINTS
   value: "false"
 # -- The port that the liveness probe listens on.
 - name: VSECM_PROBE_LIVENESS_PORT
   value: ":8081"
 # -- Enable or disable OIDC resource server. When enabled, VSecM Sentinel will
 # act as an OIDC resource server. Note that exposing VSecM Sentinel's functionality
 # through a server significantly alters the attack surface, and the decision
 # should be considered carefully. This option will create a RESTful API around VSecM
 # Sentinel. Since VSecM Sentinel is the main entry point to the system, the
 # server's security is important. Ideally, do not expose this server to the
 # public Internet and protect it with tight security controls.
 - name: VSECM_SENTINEL_ENABLE_OIDC_RESOURCE_SERVER
   value: "false"
 # -- The path where the initialization commands are mounted.
 - name: VSECM_SENTINEL_INIT_COMMAND_PATH
   value: "/opt/vsecm-sentinel/init/data"
 # -- The amount of time to wait (in milliseconds) after all
 # initialization commands are executed.
 - name: VSECM_SENTINEL_INIT_COMMAND_WAIT_AFTER_INIT_COMPLETE
   value: "0"
 # -- The amount of time to wait (in milliseconds) before executing the
 # initialization commands.
 - name: VSECM_SENTINEL_INIT_COMMAND_WAIT_BEFORE_EXEC
   value: "0"
 # -- VSecM Sentinel uses a gRPC logger to log audit events. This is the URL of the
 # gRPC logger.
 - name: VSECM_SENTINEL_LOGGER_URL
   value: "localhost:50051"
 # -- The OIDC provider's base URL. This is the URL that VSecM Sentinel will use to
 # introspect the token.
 - name: VSECM_SENTINEL_OIDC_PROVIDER_BASE_URL
   value: "http://0.0.0.0:8080/auth/realms/XXXXX/protocol/openid-connect/token/introspect"
 # -- The prefix to hint to generate secrets randomly based on regex-like patterns.
 - name: VSECM_SENTINEL_SECRET_GENERATION_PREFIX
   value: "gen:"

# Override it with an image pull secret that you need as follows:
# imagePullSecrets:
#  - name: my-registry-secret
imagePullSecrets: []

# -- The name override of the chart.
nameOverride: ""
# -- The fullname override of the chart.
fullnameOverride: ""

# -- The service account to use.
serviceAccount:
  # -- Specifies whether a service account should be created
  create: true
  # -- Annotations to add to the service account
  annotations: {}
  # -- The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: "vsecm-sentinel"

# -- Additional pod annotations.
podAnnotations: {}

# -- Pod security context overrides.
podSecurityContext: {}
  # fsGroup: 2000

resources:
  # These are default requests that can be used as a starting point.
  # Of course, benchmark your production system to determine the actual
  # requests you need.
  requests:
    memory: "20Mi"
    cpu: "5m"

# -- Autoscaling settings. Note that autoscaling does not make sense for VSecM
# Sentinel as it is a control plane component that is mainly used as a CLI
# tool. It is not a server that is expected to be running all the time.
autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

# -- The custom initialization commands that will be executed by the VSecM
# Sentinel during its initial bootstrapping. The commands are executed in the
# order they are provided. See the official documentation for more information:
# https://vsecm.com/configuration
initCommand:
  # -- Specifies whether the custom initialization commands are enabled.
  # If set to 'false', the custom initialization commands will not be executed.
  enabled: true

  # Add any initialization command here, separated by a line with only "--"
  # The command stanza MUST end with a "--".
  command: |
    exit:true
    --

  #  Example:
  #  --------
  #
  #  sleep:30001
  #  --
  #  w:keycloak-admin-secret,keycloak-db-secret
  #  n:smo-app,web-app
  #  s:gen:{"username":"admin-[a-z0-9]{6}","password":"[a-zA-Z0-9]{12}"}
  #  t:{"KEYCLOAK_ADMIN_USER":"{{.username}}","KEYCLOAK_ADMIN_PASSWORD":"{{.password}}"}
  #  --
  #  w:k8s:keycloak-db-secret
  #  n:smo-app
  #  s:gen:{"username":"admin-[a-z0-9]{6}","password":"[a-zA-Z0-9]{12}"}
  #  t:{"KEYCLOAK_DB_USER":"{{.username}}","KEYCLOAK_DB_PASSWORD":"{{.password}}"}
  #  --
  #  sleep:5000
  #  --
  #  w:keycloak
  #  n:default
  #  s:trigger-init
  #  --
