# /*
# |    Protect your secrets, protect your sensitive data.
# :    Explore VMware Secrets Manager docs at https://vsecm.com/
# </
# <>/  keep your secrets... secret
# >/
# <>/' Copyright 2023-present VMware Secrets Manager contributors.
# >/'  SPDX-License-Identifier: BSD-2-Clause
# */

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "keystone.fullname" . }}
  namespace: {{ .Values.global.vsecm.namespace }}
  labels:
    {{- include "keystone.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "keystone.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "keystone.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "keystone.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}

      priorityClassName: system-cluster-critical

      initContainers:
        - name: init-container
          image: "{{ .Values.global.registry }}/{{ .Values.global.images.initContainer.repository }}:{{ .Values.global.images.initContainer.tag }}"
          imagePullPolicy: {{ .Values.global.images.keystone.pullPolicy }}
          volumeMounts:
            - mountPath: /spire-agent-socket
              name: spire-agent-socket
              readOnly: true
          env:
            #
            # You can configure VSecM Init Container by providing
            # environment variables.
            #
            # See https://vsecm.com/configuration for more information about
            # these environment variables.
            #
            # When you don't explicitly provide env vars here, VMware Secrets Manager
            # Init Container will assume the default values outlined in the given link above.
            #
          {{- $safeInitEndpointUrlSet := false }}
          {{- $safeInitSpiffeIdPrefixSet := false }}
          {{- $workloadInitSpiffeIdPrefixSet := false }}
          {{- $vsecmInitNamespaceSet := false }}
          {{- $spireInitNamespaceSet := false }}
          {{- $spiffeTrustDomainSet := false }}
          {{- $workloadNameRegExpSet := false }}
          {{- range .Values.initEnvironments }}
            {{- if eq .name "VSECM_SAFE_ENDPOINT_URL" }}
              {{- $safeInitEndpointUrlSet = true }}
            {{- end }}
            {{- if eq .name "VSECM_SPIFFEID_PREFIX_SAFE" }}
              {{- $safeInitSpiffeIdPrefixSet = true }}
            {{- end }}
            {{- if eq .name "VSECM_SPIFFEID_PREFIX_WORKLOAD" }}
              {{- $workloadInitSpiffeIdPrefixSet = true }}
            {{- end }}
            {{ if eq .name "VSECM_NAMESPACE_SYSTEM" }}
              {{- $vsecmInitNamespaceSet = true }}
            {{- end }}
            {{ if eq .name "VSECM_NAMESPACE_SPIRE" }}
              {{- $spireInitNamespaceSet = true }}
            {{- end }}
            {{ if eq .name "SPIFFE_TRUST_DOMAIN" }}
              {{- $spiffeTrustDomainSet = true }}
            {{- end }}
            {{- if eq .name "VSECM_WORKLOAD_NAME_REGEXP" }}
              {{- $workloadNameRegExpSet = true }}
            {{- end }}
            - name: {{ .name }}
              value: {{ .value | quote }}
          {{- end }}
          {{- if not $safeInitEndpointUrlSet }}
            - name: VSECM_SAFE_ENDPOINT_URL
              value: {{ .Values.global.vsecm.safeEndpointUrl | quote }}
          {{- end }}
          {{- if not $safeInitSpiffeIdPrefixSet }}
            - name: VSECM_SPIFFEID_PREFIX_SAFE
              value: {{ .Values.global.vsecm.safeSpiffeIdPrefix | quote }}
          {{- end }}
          {{- if not $workloadInitSpiffeIdPrefixSet }}
            - name: VSECM_SPIFFEID_PREFIX_WORKLOAD
              value: {{ .Values.global.vsecm.workloadSpiffeIdPrefix | quote }}
          {{- end }}
          {{- if not $vsecmInitNamespaceSet }}
            - name: VSECM_NAMESPACE_SYSTEM
              value: {{ .Values.global.vsecm.namespace | quote }}
          {{- end }}
          {{- if not $spireInitNamespaceSet }}
            - name: VSECM_NAMESPACE_SPIRE
              value: {{ .Values.global.spire.namespace | quote }}
          {{- end }}
          {{- if not $spiffeTrustDomainSet }}
            - name: SPIFFE_TRUST_DOMAIN
              value: {{ .Values.global.spire.trustDomain | quote }}
          {{- end }}
          {{- if not $workloadNameRegExpSet }}
            - name: VSECM_WORKLOAD_NAME_REGEXP
              value: {{ .Values.global.vsecm.workloadNameRegExp | quote }}
          {{- end }}
      containers:
        - name: main
          image: "{{ .Values.global.registry }}/{{- include "keystone.repository" .}}:{{ .Values.global.images.keystone.tag }}"
          imagePullPolicy: {{ .Values.global.images.keystone.pullPolicy }}
          volumeMounts:
            - name: spire-agent-socket
              mountPath: /spire-agent-socket
              readOnly: true
          #
          # You can configure VSecM Sentinel by providing
          # environment variables.
          #
          # See https://vsecm.com/configuration for more information about
          # these environment variables.
          #
          # When you don't explicitly provide env vars here, VMware Secrets Manager
          # Sentinel will assume the default values outlined in the given link above.
          #
          env:
          {{- range .Values.environments }}
            - name: {{ .name }}
              value: {{ .value | quote }}
          {{- end }}
          resources:
            requests:
              memory: {{ .Values.resources.requests.memory }}
              cpu: {{ .Values.resources.requests.cpu }}
      volumes:
        # Using SPIFFE CSI Driver to bind to the SPIRE Agent Socket
        # ref: https://github.com/spiffe/spiffe-csi
        - name: spire-agent-socket
          csi:
            driver: "csi.spiffe.io"
            readOnly: true
