---
# Source: vsecm/charts/safe/templates/hook-preinstall-namespace.yaml
# /*
# |    Protect your secrets, protect your sensitive data.
# :    Explore VMware Secrets Manager docs at https://vsecm.com/
# </
# <>/  keep your secrets… secret
# >/
# <>/' Copyright 2023–present VMware, Inc.
# >/'  SPDX-License-Identifier: BSD-2-Clause
# */

apiVersion: v1
kind: Namespace
metadata:
  name: vsecm-system
---
# Source: vsecm/charts/safe/templates/serviceaccount.yaml
# /*
# |    Protect your secrets, protect your sensitive data.
# :    Explore VMware Secrets Manager docs at https://vsecm.com/
# </
# <>/  keep your secrets… secret
# >/
# <>/' Copyright 2023–present VMware, Inc.
# >/'  SPDX-License-Identifier: BSD-2-Clause
# */

apiVersion: v1
kind: ServiceAccount
metadata:
  name: vsecm-safe
  namespace: vsecm-system
  labels:
    helm.sh/chart: safe-0.22.2
    app.kubernetes.io/name: vsecm-safe
    app.kubernetes.io/instance: vsecm
    app.kubernetes.io/part-of: vsecm-system
    app.kubernetes.io/version: "0.22.2"
    app.kubernetes.io/managed-by: Helm
automountServiceAccountToken: true
---
# Source: vsecm/charts/sentinel/templates/serviceaccount.yaml
# /*
# |    Protect your secrets, protect your sensitive data.
# :    Explore VMware Secrets Manager docs at https://vsecm.com/
# </
# <>/  keep your secrets… secret
# >/
# <>/' Copyright 2023–present VMware, Inc.
# >/'  SPDX-License-Identifier: BSD-2-Clause
# */

apiVersion: v1
kind: ServiceAccount
metadata:
  name: vsecm-sentinel
  namespace: vsecm-system
  labels:
    helm.sh/chart: sentinel-0.22.2
    app.kubernetes.io/name: vsecm-sentinel
    app.kubernetes.io/instance: vsecm
    app.kubernetes.io/part-of: vsecm-system
    app.kubernetes.io/version: "0.22.2"
    app.kubernetes.io/managed-by: Helm
automountServiceAccountToken: false
---
# Source: vsecm/charts/safe/templates/secret.yaml
# /*
# |    Protect your secrets, protect your sensitive data.
# :    Explore VMware Secrets Manager docs at https://vsecm.com/
# </
# <>/  keep your secrets… secret
# >/
# <>/' Copyright 2023–present VMware, Inc.
# >/'  SPDX-License-Identifier: BSD-2-Clause
# */

apiVersion: v1
kind: Secret
metadata:
  name: vsecm-safe-age-key
  namespace: vsecm-system
type: Opaque
data:
  # '{}' (e30=) is a special placeholder to tell Safe that the Secret
  # is not initialized. DO NOT remove or change it.
  KEY_TXT: "e30="
---
# Source: vsecm/charts/safe/templates/hook-preinstall_role.yaml
# /*
# |    Protect your secrets, protect your sensitive data.
# :    Explore VMware Secrets Manager docs at https://vsecm.com/
# </
# <>/  keep your secrets… secret
# >/
# <>/' Copyright 2023–present VMware, Inc.
# >/'  SPDX-License-Identifier: BSD-2-Clause
# */

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: vsecm-secret-readwriter
#
# Creating a `ClusterRole` will make the role applicable to all namespaces
# within the cluster. This approach is easier to maintain, and still secure
# enough because VSecM Safe will talk only to the Secrets it knows about.
# Alternatively, you can create a `Role` for tighter control:
#
#   kind: Role
#   metadata:
#     name: vsecm-secret-readwriter
#     namespace: vsecm-system
#
##

##
#
# It is not possible to implement a more granular regex-based
# access control using RBAC. See, for example:
# https://github.com/kubernetes/kubernetes/issues/93845
#
# Also, note that you will either need to specify one role for each
# namespace, or you will need to define a ClusterRole across the cluster.
# The former approach is tedious, yet more explicit, and more secure.
#
# If you are NOT planning to use Kubernetes Secrets to sync VSecM-Safe-generated
# secrets (i.e., if VSECM_SAFE_USE_KUBERNETES_SECRETS is "false"), then
# you can limit the scope of this role as follows:
#
#    rules
#    - apiGroups: [""]
#      resources: ["secrets"]
#      resourceNames: ["vsecm-safe-age-key"]
#      verbs: ["get", "watch", "list", "update"]
#
# When the above rule is defined and when VSECM_SAFE_USE_KUBERNETES_SECRETS
# environment variable is either not set, or set to anything other than "true",
# then you can only consume VSecM-managed secrets through VSecM Safe API, either
# by using the VSecM SDK, or leveraging VSecM Sidecar—which is the recommended way.
#
##

##
#
# This `rules` setting is for legacy support (see the above discussion):
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get", "watch", "list", "update"]
#
# This `rules` configuration is the recommended, more secure, way:
#
# rules:
#   - apiGroups: [""]
#     resources: ["secrets"]
#     resourceNames: ["vsecm-safe-age-key"]
#     verbs: ["get", "watch", "list", "update"]
#
#
##
---
# Source: vsecm/charts/safe/templates/role_binding.yaml
# /*
# |    Protect your secrets, protect your sensitive data.
# :    Explore VMware Secrets Manager docs at https://vsecm.com/
# </
# <>/  keep your secrets… secret
# >/
# <>/' Copyright 2023–present VMware, Inc.
# >/'  SPDX-License-Identifier: BSD-2-Clause
# */

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: vsecm-secret-readwriter-binding
subjects:
  - kind: ServiceAccount
    name: vsecm-safe
    namespace: vsecm-system
roleRef:
  kind: ClusterRole
  name: vsecm-secret-readwriter
  apiGroup: rbac.authorization.k8s.io

##
#
# Alternatively, for a tighter security, you can define a `RoleBinding`
# instead of a `ClusterRoleBinding`. It will be more secure, yet harder to
# maintain. See the discussion about above `Role`s and `RoleBinding`s.
#
#   apiVersion: rbac.authorization.k8s.io/v1
#   kind: RoleBinding
#   metadata:
#     name: vsecm-secret-readwriter-binding
#     namespace: vsecm-system
#   subjects:
#     - kind: ServiceAccount
#       name: vsecm-safe
#       namespace: vsecm-system
#   roleRef:
#     kind: Role
#     name: vsecm-secret-readwriter
#     apiGroup: rbac.authorization.k8s.io
#
##
---
# Source: vsecm/charts/safe/templates/service.yaml
# /*
# |    Protect your secrets, protect your sensitive data.
# :    Explore VMware Secrets Manager docs at https://vsecm.com/
# </
# <>/  keep your secrets… secret
# >/
# <>/' Copyright 2023–present VMware, Inc.
# >/'  SPDX-License-Identifier: BSD-2-Clause
# */

apiVersion: v1
kind: Service
metadata:
  name: vsecm-safe
  namespace: vsecm-system
  labels:
    helm.sh/chart: safe-0.22.2
    app.kubernetes.io/name: vsecm-safe
    app.kubernetes.io/instance: vsecm
    app.kubernetes.io/part-of: vsecm-system
    app.kubernetes.io/version: "0.22.2"
    app.kubernetes.io/managed-by: Helm
spec:
  type: ClusterIP
  ports:
    - port: 8443
      targetPort: 8443
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: vsecm-safe
    app.kubernetes.io/instance: vsecm
    app.kubernetes.io/part-of: vsecm-system
---
# Source: vsecm/charts/safe/templates/Deployment.yaml
# /*
# |    Protect your secrets, protect your sensitive data.
# :    Explore VMware Secrets Manager docs at https://vsecm.com/
# </
# <>/  keep your secrets… secret
# >/
# <>/' Copyright 2023–present VMware, Inc.
# >/'  SPDX-License-Identifier: BSD-2-Clause
# */

apiVersion: apps/v1
kind: Deployment
metadata:
  name: vsecm-safe
  namespace: vsecm-system
  labels:
    helm.sh/chart: safe-0.22.2
    app.kubernetes.io/name: vsecm-safe
    app.kubernetes.io/instance: vsecm
    app.kubernetes.io/part-of: vsecm-system
    app.kubernetes.io/version: "0.22.2"
    app.kubernetes.io/managed-by: Helm
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: vsecm-safe
      app.kubernetes.io/instance: vsecm
      app.kubernetes.io/part-of: vsecm-system
  template:
    metadata:
      labels:
        app.kubernetes.io/name: vsecm-safe
        app.kubernetes.io/instance: vsecm
        app.kubernetes.io/part-of: vsecm-system
    spec:
      serviceAccountName: vsecm-safe
      securityContext:
        {}
      containers:
        - name: main
          image: "localhost:5000/vsecm-ist-fips-safe:0.22.2"
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8443
          volumeMounts:
            - name: spire-agent-socket
              mountPath: /spire-agent-socket
              readOnly: true
            - name: vsecm-data
              mountPath: /data
            - name: vsecm-age
              mountPath: /key
              readOnly: true
          #
          # You can configure VSecM Safe by providing environment variables.
          #
          # See https://vsecm.com/configuration for more information about
          # these environment variables.
          #
          # When you don’t explicitly provide env vars here, VSecM Safe
          # will assume the default values outlined in the given link above.
          #
          env:
            - name: SPIFFE_ENDPOINT_SOCKET
              value: "unix:///spire-agent-socket/agent.sock"
            - name: VSECM_LOG_LEVEL
              value: "3"
            - name: VSECM_PROBE_LIVENESS_PORT
              value: ":8081"
            - name: VSECM_PROBE_READINESS_PORT
              value: ":8082"
            - name: VSECM_SAFE_BACKING_STORE
              value: "file"
            - name: VSECM_SAFE_BOOTSTRAP_TIMEOUT
              value: "30000"
            - name: VSECM_SAFE_CRYPTO_KEY_NAME
              value: "vsecm-safe-age-key"
            - name: VSECM_SAFE_CRYPTO_KEY_PATH
              value: "/key/key.txt"
            - name: VSECM_SAFE_DATA_PATH
              value: "/data"
            - name: VSECM_SAFE_ENDPOINT_URL
              value: "https://vsecm-safe.vsecm-system.svc.cluster.local:8443/"
            - name: VSECM_SAFE_FIPS_COMPLIANT
              value: "false"
            - name: VSECM_SAFE_IV_INITIALIZATION_INTERVAL
              value: "50"
            - name: VSECM_SAFE_K8S_SECRET_BUFFER_SIZE
              value: "10"
            - name: VSECM_SAFE_K8S_SECRET_DELETE_BUFFER_SIZE
              value: "10"
            - name: VSECM_SAFE_MANUAL_KEY_INPUT
              value: "false"
            - name: VSECM_SAFE_SECRET_BACKUP_COUNT
              value: "3"
            - name: VSECM_SAFE_SECRET_BUFFER_SIZE
              value: "10"
            - name: VSECM_SAFE_SECRET_DELETE_BUFFER_SIZE
              value: "10"
            - name: VSECM_SAFE_SECRET_NAME_PREFIX
              value: "vsecm-secret-"
            - name: VSECM_SAFE_SOURCE_ACQUISITION_TIMEOUT
              value: "10000"
            - name: VSECM_SAFE_TLS_PORT
              value: ":8443"
            - name: VSECM_SAFE_USE_KUBERNETES_SECRETS
              value: "false"
            - name: VSECM_SAFE_SPIFFEID_PREFIX
              value: "spiffe://vsecm.com/workload/vsecm-safe/ns/vsecm-system/sa/vsecm-safe/n/"
            - name: VSECM_WORKLOAD_SPIFFEID_PREFIX
              value: "spiffe://vsecm.com/workload/"
            - name: VSECM_SYSTEM_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          livenessProbe:
            httpGet:
              path: /
              port: 8081
            initialDelaySeconds: 1
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /
              port: 8082
            initialDelaySeconds: 1
            periodSeconds: 10
          resources:
            {}
      volumes:
        # Using SPIFFE CSI Driver to bind to the SPIRE Agent Socket
        # ref: https://github.com/spiffe/spiffe-csi
        - name: spire-agent-socket
          csi:
            driver: "csi.spiffe.io"
            readOnly: true
        # `vsecm-data` is used to persist the encrypted backups of the secrets.
        - name: vsecm-data
          hostPath:
            path: /var/local/vsecm/data
            type: DirectoryOrCreate
        # `vsecm-age` stores the encryption keys to restore secrets from vsecm-data.
        - name: vsecm-age
          secret:
            secretName: vsecm-safe-age-key
            items:
              - key: KEY_TXT
                path: key.txt
---
# Source: vsecm/charts/sentinel/templates/Deployment.yaml
# /*
# |    Protect your secrets, protect your sensitive data.
# :    Explore VMware Secrets Manager docs at https://vsecm.com/
# </
# <>/  keep your secrets… secret
# >/
# <>/' Copyright 2023–present VMware, Inc.
# >/'  SPDX-License-Identifier: BSD-2-Clause
# */

apiVersion: apps/v1
kind: Deployment
metadata:
  name: vsecm-sentinel
  namespace: vsecm-system
  labels:
    helm.sh/chart: sentinel-0.22.2
    app.kubernetes.io/name: vsecm-sentinel
    app.kubernetes.io/instance: vsecm
    app.kubernetes.io/part-of: vsecm-system
    app.kubernetes.io/version: "0.22.2"
    app.kubernetes.io/managed-by: Helm
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: vsecm-sentinel
      app.kubernetes.io/instance: vsecm
      app.kubernetes.io/part-of: vsecm-system
  template:
    metadata:
      labels:
        app.kubernetes.io/name: vsecm-sentinel
        app.kubernetes.io/instance: vsecm
        app.kubernetes.io/part-of: vsecm-system
    spec:
      serviceAccountName: vsecm-sentinel
      securityContext:
        {}
      containers:
        - name: main
          image: "localhost:5000/vsecm-ist-fips-sentinel:0.22.2"
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - name: spire-agent-socket
              mountPath: /spire-agent-socket
              readOnly: true
          #
          # You can configure VSecM Sentinel by providing
          # environment variables.
          #
          # See https://vsecm.com/configuration for more information about
          # these environment variables.
          #
          # When you don’t explicitly provide env vars here, VMware Secrets Manager
          # Sentinel will assume the default values outlined in the given link above.
          #
          env:
            - name: SPIFFE_ENDPOINT_SOCKET
              value: "unix:///spire-agent-socket/agent.sock"
            - name: VSECM_LOG_LEVEL
              value: "3"
            - name: VSECM_PROBE_LIVENESS_PORT
              value: ":8081"
            - name: VSECM_SAFE_ENDPOINT_URL
              value: "https://vsecm-safe.vsecm-system.svc.cluster.local:8443/"
            - name: VSECM_SAFE_SPIFFEID_PREFIX
              value: "spiffe://vsecm.com/workload/vsecm-safe/ns/vsecm-system/sa/vsecm-safe/n/"
            - name: VSECM_SAFE_TLS_PORT
              value: ":8443"
            - name: VSECM_SENTINEL_SPIFFEID_PREFIX
              value: "spiffe://vsecm.com/workload/vsecm-sentinel/ns/vsecm-system/sa/vsecm-sentinel/n/"
          livenessProbe:
            httpGet:
              path: /
              port: 8081
            initialDelaySeconds: 1
            periodSeconds: 10
          resources:
            {}
      volumes:
        # Using SPIFFE CSI Driver to bind to the SPIRE Agent Socket
        # ref: https://github.com/spiffe/spiffe-csi
        - name: spire-agent-socket
          csi:
            driver: "csi.spiffe.io"
            readOnly: true
---
# Source: vsecm/charts/safe/templates/identity.yaml
# /*
# |    Protect your secrets, protect your sensitive data.
# :    Explore VMware Secrets Manager docs at https://vsecm.com/
# </
# <>/  keep your secrets… secret
# >/
# <>/' Copyright 2023–present VMware, Inc.
# >/'  SPDX-License-Identifier: BSD-2-Clause
# */

apiVersion: spire.spiffe.io/v1alpha1
kind: ClusterSPIFFEID
metadata:
  name: vsecm-safe
spec:
  spiffeIDTemplate: "spiffe://vsecm.com\
    /workload/vsecm-safe\
    /ns/{{ .PodMeta.Namespace }}\
    /sa/{{ .PodSpec.ServiceAccountName }}\
    /n/{{ .PodMeta.Name }}"
  podSelector:
    matchLabels:
      app.kubernetes.io/name: vsecm-safe
      app.kubernetes.io/part-of: vsecm-system
  workloadSelectorTemplates:
    - "k8s:ns:vsecm-system"
    - "k8s:sa:vsecm-safe"
---
# Source: vsecm/charts/sentinel/templates/identity.yaml
# /*
# |    Protect your secrets, protect your sensitive data.
# :    Explore VMware Secrets Manager docs at https://vsecm.com/
# </
# <>/  keep your secrets… secret
# >/
# <>/' Copyright 2023–present VMware, Inc.
# >/'  SPDX-License-Identifier: BSD-2-Clause
# */

apiVersion: spire.spiffe.io/v1alpha1
kind: ClusterSPIFFEID
metadata:
  name: vsecm-sentinel
spec:
  spiffeIDTemplate: "spiffe://vsecm.com\
    /workload/vsecm-sentinel\
    /ns/{{ .PodMeta.Namespace }}\
    /sa/{{ .PodSpec.ServiceAccountName }}\
    /n/{{ .PodMeta.Name }}"
  podSelector:
    matchLabels:
      app.kubernetes.io/name: vsecm-sentinel
      app.kubernetes.io/part-of: vsecm-system
  workloadSelectorTemplates:
    - "k8s:ns:vsecm-system"
    - "k8s:sa:vsecm-sentinel"
